=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require "uri"

module SwaggerClient
  class ImagesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # POSTs files to a temporary store
    # POSTs files to a temporary store
    # @param images Form/multipart file post
    # @param [Hash] opts the optional parameters
    # @return [FileResult]
    def post_images(images, opts = {})
      data, status_code, headers = post_images_with_http_info(images, opts)
      return data
    end

    # POSTs files to a temporary store
    # POSTs files to a temporary store
    # @param images Form/multipart file post
    # @param [Hash] opts the optional parameters
    # @return [Array<(FileResult, Fixnum, Hash)>] FileResult data, response status code and response headers
    def post_images_with_http_info(images, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ImagesApi#post_images ..."
      end
      
      # verify the required parameter 'images' is set
      fail "Missing the required parameter 'images' when calling post_images" if images.nil?
      
      # resource path
      local_var_path = "/images/".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = ['application/json']
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = ['application/json']
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}
      form_params["Images"] = images

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'FileResult')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ImagesApi#post_images\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
