=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require "uri"

module SwaggerClient
  class LanguagesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Get text in a specified language
    # Get text in a specified language
    # @param language_code Two-character language code, like \&quot;en\&quot; (english)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key A string used to query the language dictionary for specific values within a category.
    # @return [LanguageDictionary]
    def get_language_text(language_code, opts = {})
      data, status_code, headers = get_language_text_with_http_info(language_code, opts)
      return data
    end

    # Get text in a specified language
    # Get text in a specified language
    # @param language_code Two-character language code, like \&quot;en\&quot; (english)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :key A string used to query the language dictionary for specific values within a category.
    # @return [Array<(LanguageDictionary, Fixnum, Hash)>] LanguageDictionary data, response status code and response headers
    def get_language_text_with_http_info(language_code, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LanguagesApi#get_language_text ..."
      end
      
      # verify the required parameter 'language_code' is set
      fail "Missing the required parameter 'language_code' when calling get_language_text" if language_code.nil?
      
      # resource path
      local_var_path = "/languages/".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'languageCode'] = language_code
      query_params[:'key'] = opts[:'key'] if opts[:'key']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = ['application/json']
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = ['application/json']
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'LanguageDictionary')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LanguagesApi#get_language_text\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
