=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require "uri"

module SwaggerClient
  class UserinfoApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Get the user&#39;s language code and country based upon IP
    # IP-based user info lookup
    # @param [Hash] opts the optional parameters
    # @option opts [String] :language_code Two-character language code, if known at the time.
    # @return [UserInfo]
    def get_userinfo(opts = {})
      data, status_code, headers = get_userinfo_with_http_info(opts)
      return data
    end

    # Get the user&#39;s language code and country based upon IP
    # IP-based user info lookup
    # @param [Hash] opts the optional parameters
    # @option opts [String] :language_code Two-character language code, if known at the time.
    # @return [Array<(UserInfo, Fixnum, Hash)>] UserInfo data, response status code and response headers
    def get_userinfo_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserinfoApi#get_userinfo ..."
      end
      
      # resource path
      local_var_path = "/userinfo/".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'languageCode'] = opts[:'language_code'] if opts[:'language_code']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = ['application/json']
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = ['application/json']
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'UserInfo')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserinfoApi#get_userinfo\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
