=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CountriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CountriesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CountriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountriesApi' do
    it 'should create an instact of CountriesApi' do
      @instance.should be_a(SwaggerClient::CountriesApi)
    end
  end

  # unit tests for countries
  # Get a list of supported countries. Output is in specified language.
  # Get a list of supported countries. Output is in specified language.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code Two-character language code, like \&quot;en\&quot; (english)
  # @option opts [String] :key A string used to query the language dictionary for specific values within a category.
  # @return [CountryList]
  describe 'countries test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
