=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ImagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImagesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ImagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImagesApi' do
    it 'should create an instact of ImagesApi' do
      @instance.should be_a(SwaggerClient::ImagesApi)
    end
  end

  # unit tests for post_images
  # POSTs files to a temporary store
  # POSTs files to a temporary store
  # @param images Form/multipart file post
  # @param [Hash] opts the optional parameters
  # @return [FileResult]
  describe 'post_images test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
