=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LanguagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LanguagesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LanguagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LanguagesApi' do
    it 'should create an instact of LanguagesApi' do
      @instance.should be_a(SwaggerClient::LanguagesApi)
    end
  end

  # unit tests for get_language_text
  # Get text in a specified language
  # Get text in a specified language
  # @param language_code Two-character language code, like \&quot;en\&quot; (english)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key A string used to query the language dictionary for specific values within a category.
  # @return [LanguageDictionary]
  describe 'get_language_text test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
