=begin
Gooten API

An overview of the various API methods that Gooten offers, including examples of each.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for GootenApiClient::PaymentvalidationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentvalidationApi' do
  before do
    # run before each test
    @instance = GootenApiClient::PaymentvalidationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentvalidationApi' do
    it 'should create an instact of PaymentvalidationApi' do
      @instance.should be_a(GootenApiClient::PaymentvalidationApi)
    end
  end

  # unit tests for paymentvalidation
  # Submit payment validation for PayPal
  # Submit payment validation for PayPal
  # @param order_id Order Id returned from orders/POST
  # @param pay_pal_key The PayPal key returned from the Mobile SDK
  # @param [Hash] opts the optional parameters
  # @return [PaymentValidationResponse]
  describe 'paymentvalidation test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
