=begin
Gooten API


An overview of the various API methods that Gooten offers, including examples of each.


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git




=end

require 'spec_helper'
require 'json'

# Unit tests for GootenApiClient::ProducttemplatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProducttemplatesApi' do
  before do
    # run before each test
    @instance = GootenApiClient::ProducttemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProducttemplatesApi' do
    it 'should create an instact of ProducttemplatesApi' do
      @instance.should be_a(GootenApiClient::ProducttemplatesApi)
    end
  end


  # unit tests for get_producttemplates
  # Get a list of product templates
  # Get a list of product templates.
  # @param sku Productvariant sku.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code Two-character language code, defaults to \&quot;en\&quot; (english)
  # @return [ProductBuildInfoResponse]
  describe 'get_producttemplates test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


end

