=begin
Gooten API

An overview of the various API methods that Gooten offers, including examples of each.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for GootenApiClient::UserinfoApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserinfoApi' do
  before do
    # run before each test
    @instance = GootenApiClient::UserinfoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserinfoApi' do
    it 'should create an instact of UserinfoApi' do
      @instance.should be_a(GootenApiClient::UserinfoApi)
    end
  end

  # unit tests for get_userinfo
  # Get the user&#39;s language code and country based upon IP
  # IP-based user info lookup
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code Two-character language code, if known at the time.
  # @return [UserInfo]
  describe 'get_userinfo test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
