=begin
Gooten API

An overview of the various API methods that Gooten offers, including examples of each.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GootenApiClient::CountryList
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CountryList' do
  before do
    # run before each test
    @instance = GootenApiClient::CountryList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountryList' do
    it 'should create an instact of CountryList' do
      @instance.should be_a(GootenApiClient::CountryList) 
    end
  end
  describe 'test attribute "countries"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

