=begin
Gooten API


An overview of the various API methods that Gooten offers, including examples of each.


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git




=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GootenApiClient::OrderItemImage
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrderItemImage' do
  before do
    # run before each test
    @instance = GootenApiClient::OrderItemImage.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderItemImage' do
    it 'should create an instact of OrderItemImage' do
      @instance.should be_a(GootenApiClient::OrderItemImage) 
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "index"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "thumbnail_url"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "manip_command"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "space_id"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


end

