=begin
Gooten API


An overview of the various API methods that Gooten offers, including examples of each.


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git




=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GootenApiClient::PostSubmittedItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostSubmittedItem' do
  before do
    # run before each test
    @instance = GootenApiClient::PostSubmittedItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostSubmittedItem' do
    it 'should create an instact of PostSubmittedItem' do
      @instance.should be_a(GootenApiClient::PostSubmittedItem) 
    end
  end

  describe 'test attribute "sku"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "product_id"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "product"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "quantity"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "status"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "tracking_number"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "tracking_url"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "ship_carrier_name"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "price"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "discount_amount"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "source_id"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "meta"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "shipments"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


end

