=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PreconfiguredProductsInsertResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::PreconfiguredProductsInsertResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PreconfiguredProductsInsertResponse' do
    it 'should create an instact of PreconfiguredProductsInsertResponse' do
      @instance.should be_a(SwaggerClient::PreconfiguredProductsInsertResponse) 
    end
  end
end

