=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductOptionValueSettings' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductOptionValueSettings.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductOptionValueSettings' do
    it 'should create an instact of ProductOptionValueSettings' do
      @instance.should be_a(SwaggerClient::ProductOptionValueSettings) 
    end
  end
  describe 'test attribute "icon_url"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "icon_type"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "color_rgba"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

