=begin
Gooten API


An overview of the various API methods that Gooten offers, including examples of each.


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git




=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GootenApiClient::Shipment
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Shipment' do
  before do
    # run before each test
    @instance = GootenApiClient::Shipment.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Shipment' do
    it 'should create an instact of Shipment' do
      @instance.should be_a(GootenApiClient::Shipment) 
    end
  end

  describe 'test attribute "tracking_number"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "tracking_url"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


  describe 'test attribute "ship_carrier_name"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end


end

