=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ValidationFailure' do
  before do
    # run before each test
    @instance = SwaggerClient::ValidationFailure.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ValidationFailure' do
    it 'should create an instact of ValidationFailure' do
      @instance.should be_a(SwaggerClient::ValidationFailure) 
    end
  end
  describe 'test attribute "property_name"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "error_message"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "attempted_value"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

