=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class PostSubmittedOrder
    # The unique ID we use within our system.
    attr_accessor :id

    # A short, non-unique ID that is optionally used for customer service.
    attr_accessor :nice_id

    # Partner's internal ID-- entirely optional
    attr_accessor :souce_id

    attr_accessor :items

    attr_accessor :total

    attr_accessor :shipping_total

    attr_accessor :discount_amount

    attr_accessor :discount_code

    attr_accessor :billing_address

    attr_accessor :shipping_address

    # An optional Map<string,string> of misc properties.
    attr_accessor :meta

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'id' => :'Id',
        
        :'nice_id' => :'NiceId',
        
        :'souce_id' => :'SouceId',
        
        :'items' => :'Items',
        
        :'total' => :'Total',
        
        :'shipping_total' => :'ShippingTotal',
        
        :'discount_amount' => :'DiscountAmount',
        
        :'discount_code' => :'DiscountCode',
        
        :'billing_address' => :'BillingAddress',
        
        :'shipping_address' => :'ShippingAddress',
        
        :'meta' => :'Meta'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'nice_id' => :'String',
        :'souce_id' => :'String',
        :'items' => :'Array<PostSubmittedItem>',
        :'total' => :'ProductPriceInfo',
        :'shipping_total' => :'ProductPriceInfo',
        :'discount_amount' => :'ProductPriceInfo',
        :'discount_code' => :'String',
        :'billing_address' => :'ShipToAddress',
        :'shipping_address' => :'ShipToAddress',
        :'meta' => :'Meta'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'Id']
        self.id = attributes[:'Id']
      end
      
      if attributes[:'NiceId']
        self.nice_id = attributes[:'NiceId']
      end
      
      if attributes[:'SouceId']
        self.souce_id = attributes[:'SouceId']
      end
      
      if attributes[:'Items']
        if (value = attributes[:'Items']).is_a?(Array)
          self.items = value
        end
      end
      
      if attributes[:'Total']
        self.total = attributes[:'Total']
      end
      
      if attributes[:'ShippingTotal']
        self.shipping_total = attributes[:'ShippingTotal']
      end
      
      if attributes[:'DiscountAmount']
        self.discount_amount = attributes[:'DiscountAmount']
      end
      
      if attributes[:'DiscountCode']
        self.discount_code = attributes[:'DiscountCode']
      end
      
      if attributes[:'BillingAddress']
        self.billing_address = attributes[:'BillingAddress']
      end
      
      if attributes[:'ShippingAddress']
        self.shipping_address = attributes[:'ShippingAddress']
      end
      
      if attributes[:'Meta']
        self.meta = attributes[:'Meta']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          nice_id == o.nice_id &&
          souce_id == o.souce_id &&
          items == o.items &&
          total == o.total &&
          shipping_total == o.shipping_total &&
          discount_amount == o.discount_amount &&
          discount_code == o.discount_code &&
          billing_address == o.billing_address &&
          shipping_address == o.shipping_address &&
          meta == o.meta
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [id, nice_id, souce_id, items, total, shipping_total, discount_amount, discount_code, billing_address, shipping_address, meta].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
