=begin


OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class ShipEstimate
    attr_accessor :min_price

    attr_accessor :max_price

    attr_accessor :vendor_country_code

    attr_accessor :can_ship_expedited

    attr_accessor :est_ship_days

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'min_price' => :'MinPrice',
        
        :'max_price' => :'MaxPrice',
        
        :'vendor_country_code' => :'VendorCountryCode',
        
        :'can_ship_expedited' => :'CanShipExpedited',
        
        :'est_ship_days' => :'EstShipDays'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'min_price' => :'ShipPrice',
        :'max_price' => :'ShipPrice',
        :'vendor_country_code' => :'String',
        :'can_ship_expedited' => :'BOOLEAN',
        :'est_ship_days' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'MinPrice']
        self.min_price = attributes[:'MinPrice']
      end
      
      if attributes[:'MaxPrice']
        self.max_price = attributes[:'MaxPrice']
      end
      
      if attributes[:'VendorCountryCode']
        self.vendor_country_code = attributes[:'VendorCountryCode']
      end
      
      if attributes[:'CanShipExpedited']
        self.can_ship_expedited = attributes[:'CanShipExpedited']
      end
      
      if attributes[:'EstShipDays']
        self.est_ship_days = attributes[:'EstShipDays']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          min_price == o.min_price &&
          max_price == o.max_price &&
          vendor_country_code == o.vendor_country_code &&
          can_ship_expedited == o.can_ship_expedited &&
          est_ship_days == o.est_ship_days
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [min_price, max_price, vendor_country_code, can_ship_expedited, est_ship_days].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
