=begin
Gooten API

An overview of the various API methods that Gooten offers, including examples of each.

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module GootenApiClient
  class ShipOption
    # The ID that can be passed into the /orders POST endpoing as ShipCarrierMethodId to specify an item's shipping method.
    attr_accessor :id

    attr_accessor :method_type

    attr_accessor :method_id

    attr_accessor :name

    attr_accessor :carrier_name

    attr_accessor :carrier_logo_url

    attr_accessor :price

    attr_accessor :partner_price

    attr_accessor :est_business_days_til_delivery

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'id' => :'Id',
        
        :'method_type' => :'MethodType',
        
        :'method_id' => :'MethodId',
        
        :'name' => :'Name',
        
        :'carrier_name' => :'CarrierName',
        
        :'carrier_logo_url' => :'CarrierLogoUrl',
        
        :'price' => :'Price',
        
        :'partner_price' => :'PartnerPrice',
        
        :'est_business_days_til_delivery' => :'EstBusinessDaysTilDelivery'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'method_type' => :'String',
        :'method_id' => :'Integer',
        :'name' => :'String',
        :'carrier_name' => :'String',
        :'carrier_logo_url' => :'String',
        :'price' => :'ShipPrice',
        :'partner_price' => :'ShipPrice',
        :'est_business_days_til_delivery' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'Id']
        self.id = attributes[:'Id']
      end
      
      if attributes[:'MethodType']
        self.method_type = attributes[:'MethodType']
      end
      
      if attributes[:'MethodId']
        self.method_id = attributes[:'MethodId']
      end
      
      if attributes[:'Name']
        self.name = attributes[:'Name']
      end
      
      if attributes[:'CarrierName']
        self.carrier_name = attributes[:'CarrierName']
      end
      
      if attributes[:'CarrierLogoUrl']
        self.carrier_logo_url = attributes[:'CarrierLogoUrl']
      end
      
      if attributes[:'Price']
        self.price = attributes[:'Price']
      end
      
      if attributes[:'PartnerPrice']
        self.partner_price = attributes[:'PartnerPrice']
      end
      
      if attributes[:'EstBusinessDaysTilDelivery']
        self.est_business_days_til_delivery = attributes[:'EstBusinessDaysTilDelivery']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          method_type == o.method_type &&
          method_id == o.method_id &&
          name == o.name &&
          carrier_name == o.carrier_name &&
          carrier_logo_url == o.carrier_logo_url &&
          price == o.price &&
          partner_price == o.partner_price &&
          est_business_days_til_delivery == o.est_business_days_til_delivery
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [id, method_type, method_id, name, carrier_name, carrier_logo_url, price, partner_price, est_business_days_til_delivery].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = GootenApiClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
